"""Generate run_classifier_dev_STANDALONE.ipynb — a single-file upload.

Embeds the current classifier_lib.py into the runner notebook as a
`%%writefile classifier_lib.py` bootstrap cell, so uploading ONE .ipynb
to Minerva is enough: running the first code cell materializes
classifier_lib.py on disk, and every subsequent cell (including the
`from classifier_lib import ...`) works unchanged.

classifier_lib.py stays the single source of truth: regenerate after any
lib change with

    python3 make_standalone.py

The bootstrap cell records the lib's SHA-256 so a stale standalone is
detectable against run metadata.
"""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).parent
RUNNER = ROOT / "run_classifier_dev.ipynb"
LIB = ROOT / "classifier_lib.py"
OUT = ROOT / "run_classifier_dev_STANDALONE.ipynb"


def main() -> None:
    lib_source = LIB.read_text()
    lib_sha = hashlib.sha256(lib_source.encode()).hexdigest()
    nb = json.loads(RUNNER.read_text())

    bootstrap_md = {
        "cell_type": "markdown",
        "id": "standalone-note",
        "metadata": {},
        "source": (
            "## 0. STANDALONE build — bootstrap classifier_lib.py\n"
            "\n"
            "This notebook was generated by `make_standalone.py` and embeds "
            "`classifier_lib.py` (sha256 `" + lib_sha[:16] + "…`). Run the "
            "next cell FIRST — it writes `classifier_lib.py` to the working "
            "directory so the import below succeeds.\n"
            "\n"
            "**Do not edit the embedded library here.** Edit "
            "`classifier_lib.py` in the repo and regenerate. If this file "
            "and the repo disagree, the repo wins."
        ),
    }
    bootstrap_code = {
        "cell_type": "code",
        "execution_count": None,
        "id": "standalone-bootstrap",
        "metadata": {},
        "outputs": [],
        "source": "%%writefile classifier_lib.py\n" + lib_source,
    }

    # Insert after the intro markdown cell (index 0).
    nb["cells"] = [nb["cells"][0], bootstrap_md, bootstrap_code] + nb["cells"][1:]
    OUT.write_text(json.dumps(nb, indent=1))
    print(f"wrote {OUT.name} (lib sha256 {lib_sha[:16]}…, {len(nb['cells'])} cells)")


if __name__ == "__main__":
    main()
